/// Decoder for the Discuz! "antitheft" (防采集) challenge page.
///
/// Since the forum server upgraded to Discuz! X5, opening the first page of a thread
/// (`forum.php?mod=viewthread&tid=xxx`) may return a small html page containing only an
/// obfuscated javascript instead of the real thread content. Browsers run that script and
/// get redirected to the same url with an extra `_dsign=xxxxxxxx` query parameter, then the
/// server responds with the real page.
///
/// The obfuscated script is generated by `source/class/helper/helper_antitheft.php` in Discuz!:
///
/// 1. The target url (current path + query + `&_dsign=<sign>`) is split into fragments of
///    1 to 3 characters.
/// 2. Each fragment is wrapped in one of seven fixed code patterns: a plain string literal,
///    a variable, a function returning the literal, a function whose *name* is the fragment
///    (resolved through `getName()`), or an IIFE returning the literal / its argument.
/// 3. All the definitions are shuffled and followed by a final statement that concatenates all
///    fragments and assigns the result to `location` (or calls `location.replace`, etc.).
///
/// The sign itself is `substr(md5($tid . 'tid' . $authkey), 0, 8)` and depends on a server-side
/// secret, so it can NOT be computed locally. Instead, we statically evaluate the script here
/// without a javascript engine: find the final concatenation expression and resolve every
/// term with the rules above.
///
/// The sign is constant for a given thread, so it can be cached and reused.
library;

/// Result of decoding an antitheft challenge page.
final class AntitheftChallenge {
  /// Constructor.
  const AntitheftChallenge({required this.redirectUrl, required this.dsign});

  /// Full url the browser is expected to redirect to, including `_dsign`.
  ///
  /// It's a relative url (`/forum.php?mod=viewthread&tid=1&_dsign=xxxx`).
  final String redirectUrl;

  /// The `_dsign` value.
  final String dsign;

  @override
  String toString() => 'AntitheftChallenge(redirectUrl=$redirectUrl, dsign=$dsign)';
}

/// Static evaluator for the antitheft challenge script.
abstract final class AntitheftDecoder {
  /// Name of the query parameter carrying the sign.
  static const dsignKey = '_dsign';

  /// Text that only exists in the challenge page, used to quickly identify it.
  static const _marker = 'function getName(){var caller=getName.caller;';

  static final _scriptRe = RegExp('<script type="text/javascript">(.*?)</script>', dotAll: true);

  /// The statement doing the redirect, one of:
  ///
  /// * `location.href=`
  /// * `location=`
  /// * `location[HREF_VAR]=`
  /// * `LOCATION_VAR[HREF_VAR]=`
  /// * `location.replace(`
  /// * `location.assign(`
  /// * `location[REPLACE_OR_ASSIGN_VAR](`
  ///
  /// where `LOCATION_VAR` is `_` followed by 5 random alphanumeric chars.
  static final _headerRe = RegExp(
    r'(?:location\.href=|location=|location\[\w+\]=|_[0-9A-Za-z]{5}\[\w+\]=|location\.replace\(|location\.assign\(|location\[\w+\]\()',
  );

  static final _dsignRe = RegExp('$dsignKey=([0-9a-f]{8})');

  /// Check whether [html] is a challenge page.
  ///
  /// Only do a quick and cheap check.
  static bool isChallenge(String? html) {
    if (html == null || html.length > 20480) {
      return false;
    }
    return html.contains(_marker);
  }

  /// Decode the challenge [html].
  ///
  /// Return null if failed to decode.
  static AntitheftChallenge? decode(String html) {
    final js = _scriptRe.firstMatch(html)?.group(1);
    if (js == null) {
      return null;
    }
    final header = _headerRe.firstMatch(js);
    if (header == null) {
      return null;
    }

    // Take the expression from the end of header till the first ';' or unbalanced ')' at top level.
    final rest = js.substring(header.end);
    var depth = 0;
    String? quote;
    var end = rest.length;
    for (var i = 0; i < rest.length; i++) {
      final ch = rest[i];
      if (quote != null) {
        if (ch == quote) {
          quote = null;
        }
        continue;
      }
      if (ch == "'" || ch == '"') {
        quote = ch;
      } else if (ch == '(') {
        depth += 1;
      } else if (ch == ')') {
        depth -= 1;
        if (depth < 0) {
          end = i;
          break;
        }
      } else if (ch == ';' && depth == 0) {
        end = i;
        break;
      }
    }
    final expr = rest.substring(0, end);

    final buffer = StringBuffer();
    for (final term in _splitTerms(expr)) {
      final value = _resolve(term.trim(), js);
      if (value == null) {
        return null;
      }
      buffer.write(value);
    }
    final url = buffer.toString();
    final dsign = _dsignRe.firstMatch(url)?.group(1);
    if (dsign == null) {
      return null;
    }
    return AntitheftChallenge(redirectUrl: url, dsign: dsign);
  }

  /// Split [expr] on top-level `+`.
  static List<String> _splitTerms(String expr) {
    final terms = <String>[];
    final current = StringBuffer();
    var depth = 0;
    String? quote;
    for (var i = 0; i < expr.length; i++) {
      final ch = expr[i];
      if (quote != null) {
        current.write(ch);
        if (ch == quote) {
          quote = null;
        }
        continue;
      }
      if (ch == "'" || ch == '"') {
        quote = ch;
        current.write(ch);
        continue;
      }
      if (ch == '(') {
        depth += 1;
      } else if (ch == ')') {
        depth -= 1;
      }
      if (ch == '+' && depth == 0) {
        terms.add(current.toString());
        current.clear();
      } else {
        current.write(ch);
      }
    }
    terms.add(current.toString());
    return terms;
  }

  static final _literalRe = RegExp(r"^'([^']*)'$");
  static final _iifeArgRe = RegExp(r"\)\('([^']*)'\)$");
  static final _returnLiteralRe = RegExp("return '([^']*)'");
  static final _callWithArgRe = RegExp(r"^(\w+)\('([^']*)'\)$");
  static final _callNoArgRe = RegExp(r'^(\w+)\(\)$');
  static final _identifierRe = RegExp(r'^\w+$');
  static final _getNameRe = RegExp(r'function (\w+)\(\)\{return getName\(\);\}');

  /// Resolve a single [term] into the string fragment it produces.
  static String? _resolve(String term, String js) {
    // 'literal'
    final literal = _literalRe.firstMatch(term);
    if (literal != null) {
      return literal.group(1);
    }

    // (function(x_){...return x_})('val') or (function(){...return 'val'...})()
    if (term.startsWith('(function')) {
      return _iifeArgRe.firstMatch(term)?.group(1) ?? _returnLiteralRe.firstMatch(term)?.group(1);
    }

    // name('arg')
    final callWithArg = _callWithArgRe.firstMatch(term);
    if (callWithArg != null) {
      final body = _findDefinition(callWithArg.group(1)!, js);
      if (body == null) {
        return null;
      }
      // The fragment is the name of the inner function calling getName().
      final byName = _getNameRe.firstMatch(body)?.group(1);
      if (byName != null) {
        return byName;
      }
      // Otherwise the function returns its argument.
      return callWithArg.group(2);
    }

    // name()
    final callNoArg = _callNoArgRe.firstMatch(term);
    if (callNoArg != null) {
      final body = _findDefinition(callNoArg.group(1)!, js);
      if (body == null) {
        return null;
      }
      return _returnLiteralRe.firstMatch(body)?.group(1);
    }

    // bare variable: name='val';
    if (_identifierRe.hasMatch(term)) {
      return RegExp("(?<![\\w\$])${RegExp.escape(term)}='([^']*)';").firstMatch(js)?.group(1);
    }

    return null;
  }

  /// Find the definition body of function [name], either `function name(...){...}` or
  /// `name=function(...){...}`, with balanced braces.
  static String? _findDefinition(String name, String js) {
    final escaped = RegExp.escape(name);
    final match = RegExp('(?<![\\w\$])(?:function $escaped\\(|$escaped=function\\()').firstMatch(js);
    if (match == null) {
      return null;
    }
    final start = js.indexOf('{', match.end);
    if (start < 0) {
      return null;
    }
    var depth = 0;
    for (var i = start; i < js.length; i++) {
      final ch = js[i];
      if (ch == '{') {
        depth += 1;
      } else if (ch == '}') {
        depth -= 1;
        if (depth == 0) {
          return js.substring(match.start, i + 1);
        }
      }
    }
    return null;
  }
}
